# Generated by Django 6.0.6 on 2026-06-29 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_hp', models.IntegerField()),
                ('base_mana', models.IntegerField()),
                ('base_strength', models.IntegerField()),
                ('base_agility', models.IntegerField()),
                ('base_intelligence', models.IntegerField()),
                ('hp_growth', models.FloatField()),
                ('mana_growth', models.FloatField()),
                ('strength_growth', models.FloatField()),
                ('agility_growth', models.FloatField()),
                ('intelligence_growth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hp_bonus', models.IntegerField(default=0)),
                ('mana_bonus', models.IntegerField(default=0)),
                ('strength_bonus', models.IntegerField(default=0)),
                ('agility_bonus', models.IntegerField(default=0)),
                ('intelligence_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=10)),
                ('agility', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.characterclass')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.race')),
            ],
        ),
    ]
