# Generated by Django 6.0.6 on 2026-06-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_race_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('SWORD', 'Sword'), ('AXE', 'Axe'), ('DAGGER', 'Dagger'), ('BOW', 'Bow'), ('STAFF', 'Staff'), ('SHIELD', 'Shield'), ('HELMET', 'Helmet'), ('CHESTPLATE', 'Chestplate'), ('LEGGINGS', 'Leggings'), ('BOOTS', 'Boots'), ('GLOVES', 'Gloves'), ('RING', 'Ring'), ('NECKLACE', 'Necklace'), ('POTION', 'Potion'), ('MATERIAL', 'Material'), ('QUEST_ITEM', 'Quest Item')], max_length=20)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary'), ('MYTHIC', 'Mythic')], default='COMMON', max_length=20)),
                ('required_level', models.PositiveIntegerField(default=1)),
                ('buy_price', models.PositiveIntegerField(default=0)),
                ('sell_price', models.PositiveIntegerField(default=0)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='items/icons/')),
            ],
        ),
        migrations.RenameField(
            model_name='character',
            old_name='hp',
            new_name='current_hp',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='mana',
            new_name='current_mana',
        ),
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='max_mana',
            field=models.IntegerField(default=0),
        ),
    ]
