# Generated by Django 6.0.6 on 2026-07-04 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_item_rename_hp_character_current_hp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Poziom')),
                ('max_hp', models.IntegerField(default=10, verbose_name='Maksymalne HP')),
                ('attack', models.IntegerField(default=1, verbose_name='Atak')),
                ('defense', models.IntegerField(default=0, verbose_name='Obrona')),
                ('experience_reward', models.IntegerField(default=1, verbose_name='Nagroda XP')),
                ('gold_reward', models.IntegerField(default=0, verbose_name='Nagroda złota')),
                ('is_boss', models.BooleanField(default=False, verbose_name='Boss')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_stat',
            field=models.CharField(choices=[('NONE', 'Brak'), ('STRENGTH', 'Siła'), ('AGILITY', 'Zręczność'), ('INTELLIGENCE', 'Inteligencja'), ('HP', 'HP'), ('MANA', 'Mana')], default='NONE', max_length=20, verbose_name='Bonus do statystyki'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_value',
            field=models.IntegerField(default=0, verbose_name='Wartość bonusu'),
        ),
        migrations.AddField(
            model_name='item',
            name='heal_amount',
            field=models.IntegerField(default=0, verbose_name='Leczenie hp'),
        ),
        migrations.AddField(
            model_name='item',
            name='power',
            field=models.IntegerField(default=0, verbose_name='Moc (obrażenia/obrona)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='agility',
            field=models.IntegerField(default=10, verbose_name='Zręczność'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.characterclass', verbose_name='Klasa postaci'),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_hp',
            field=models.IntegerField(default=100, verbose_name='Aktualne HP'),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_mana',
            field=models.IntegerField(default=0, verbose_name='Aktualna mana'),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Doświadczenie'),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=10, verbose_name='Inteligencja'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Poziom'),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(default=100, verbose_name='Maksymalne HP'),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_mana',
            field=models.IntegerField(default=0, verbose_name='Maksymalna mana'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.race', verbose_name='Rasa'),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=10, verbose_name='Siła'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='agility_growth',
            field=models.FloatField(verbose_name='Przyrost zręczności'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='base_agility',
            field=models.IntegerField(verbose_name='Zręczność bazowa'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='base_hp',
            field=models.IntegerField(verbose_name='Bazowe HP'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='base_intelligence',
            field=models.IntegerField(verbose_name='Inteligencja bazowa'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='base_mana',
            field=models.IntegerField(verbose_name='Bazowa mana'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='base_strength',
            field=models.IntegerField(verbose_name='Siła bazowa'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='hp_growth',
            field=models.FloatField(verbose_name='Przyrost HP'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='intelligence_growth',
            field=models.FloatField(verbose_name='Przyrost inteligencji'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='mana_growth',
            field=models.FloatField(verbose_name='Przyrost many'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='strength_growth',
            field=models.FloatField(verbose_name='Przyrost siły'),
        ),
        migrations.AlterField(
            model_name='item',
            name='buy_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Cena zakupu'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='items/icons/', verbose_name='Ikona'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('COMMON', 'Zwykły'), ('UNCOMMON', 'Niepospolity'), ('RARE', 'Rzadki'), ('EPIC', 'Epicki'), ('LEGENDARY', 'Legendarny')], default='COMMON', max_length=20, verbose_name='Rzadkość'),
        ),
        migrations.AlterField(
            model_name='item',
            name='required_level',
            field=models.PositiveIntegerField(default=1, verbose_name='Wymagany poziom'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Cena sprzedaży'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('SWORD', 'Miecz'), ('BOW', 'Łuk'), ('STAFF', 'Laska'), ('SHIELD', 'Tarcza'), ('HELMET', 'Hełm'), ('ARMOR', 'Pancerz'), ('LEGGINGS', 'Spodnie'), ('GLOVES', 'Rękawice'), ('BOOTS', 'Buty'), ('POTION', 'Mikstura'), ('MATERIAL', 'Materiał'), ('QUEST_ITEM', 'Przedmiot fabularny')], max_length=20, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='race',
            name='agility_bonus',
            field=models.IntegerField(default=0, verbose_name='Bonus do zręczności'),
        ),
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='race',
            name='hp_bonus',
            field=models.IntegerField(default=0, verbose_name='Bonus do HP'),
        ),
        migrations.AlterField(
            model_name='race',
            name='intelligence_bonus',
            field=models.IntegerField(default=0, verbose_name='Bonus do inteligencji'),
        ),
        migrations.AlterField(
            model_name='race',
            name='mana_bonus',
            field=models.IntegerField(default=0, verbose_name='Bonus do many'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='race',
            name='strength_bonus',
            field=models.IntegerField(default=0, verbose_name='Bonus do siły'),
        ),
    ]
