# Generated by Django 6.0.6 on 2026-07-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_enemy_item_bonus_stat_item_bonus_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_current_hp', models.IntegerField(verbose_name='Aktualne HP postaci')),
                ('enemy_current_hp', models.IntegerField(verbose_name='Aktualne HP postaci')),
                ('status', models.CharField(choices=[('ONGOING', 'W trakcie'), ('WON', 'Wygrana'), ('LOSE', 'Przegrana')], default='ONGOING', max_length=20, verbose_name='Status')),
                ('turn_number', models.PositiveIntegerField(default=1, verbose_name='Numer tury')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character', verbose_name='Postać')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.enemy', verbose_name='Przeciwnik')),
            ],
        ),
    ]
