# Generated by Django 6.0.6 on 2026-07-05 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='starting_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.item', verbose_name='Broń startowa'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_armor', to='game.item', verbose_name='Pancerz')),
                ('boots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_boots', to='game.item', verbose_name='Buty')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='game.character', verbose_name='Postać')),
                ('gloves', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_gloves', to='game.item', verbose_name='Rękawice')),
                ('helmet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_helmet', to='game.item', verbose_name='Hełm')),
                ('leggings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_leggings', to='game.item', verbose_name='Spodnie')),
                ('shield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_shield', to='game.item', verbose_name='Tarcza')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_weapon', to='game.item', verbose_name='Broń')),
            ],
            options={
                'verbose_name': 'Ekwipunek',
                'verbose_name_plural': 'Ekwipunki',
            },
        ),
    ]
