# Generated by Django 6.0.6 on 2026-07-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_characterclass_starting_weapon_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0, verbose_name='Złoto'),
        ),
    ]
