# Generated by Django 6.0.6 on 2026-07-05 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_character_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='game.character', verbose_name='Postać')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='Przedmioty')),
            ],
            options={
                'verbose_name': 'Przedmioty w ekwipunku',
                'verbose_name_plural': 'Przedmioty w ekwipunku',
                'unique_together': {('character', 'item')},
            },
        ),
    ]
