# Generated by Django 6.0.6 on 2026-08-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_battle_character_current_mana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='enemy_current_hp',
            field=models.IntegerField(verbose_name='Aktualne HP przeciwnika'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bonus_stat',
            field=models.CharField(choices=[('NONE', 'Brak'), ('STRENGTH', 'Siła'), ('AGILITY', 'Zręczność'), ('INTELLIGENCE', 'Inteligencja'), ('HP', 'Punkty życia'), ('MANA', 'Mana')], default='NONE', max_length=20, verbose_name='Bonus do statystyki'),
        ),
    ]
